{% set name = "sympow" %}
{% set version = "3.0.0" %}
{% set sha256 = "fb3cbb6989c0c42eb383eae3e4d53508e050c8b9eeb18a1469b4a354abbdf556" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:  https://salsa.debian.org/science-team/sympow/-/archive/upstream/{{ version }}/sympow-upstream-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-OSX-apparently-does-not-know-about-t.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - pari

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
    - help2man
    - make
  host:
    - pari
  run:
    # new_data invokes PARI's GP
    - pari

test:
  commands:
    - sympow -help
    - sympow -new_data 2

about:
  home: http://files.sagemath.org/spkg/upstream/sympow/index.html
  license: BSD-variant
  license_family: BSD
  license_file: {{ SRC_DIR }}/COPYING
  summary: A package to compute special values of symmetric power elliptic curve L-functions

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
