{% set name = "sympow" %}
{% set version = "2.023.7" %}
{% set sha256 = "f19a2b428c573f9e4c36a97b736b562e76f4bfc354497abaeb7140632bef3400" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/rezozer/forks/sympow/-/archive/v{{ version }}/sympow-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0000-cross.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - pari

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - libtool
    - autoconf
    - automake
    - help2man
    - make
    - pari  # [build_platform != target_platform]
  host:
    - pari
  run:
    # new_data invokes PARI's GP
    - pari

test:
  commands:
    - sympow -help
    - sympow -new_data 2

about:
  home: http://files.sagemath.org/spkg/upstream/sympow/index.html
  license: LicenseRef-BSD-like
  license_family: BSD
  license_file: {{ SRC_DIR }}/COPYING
  summary: A package to compute special values of symmetric power elliptic curve L-functions

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
